export const UTILITY_DATA_TIME = process.env.REACT_APP_API_CALL_TIME || 60000;
export const CHANGE_DB_METER_TYPE =
  process.env.REACT_APP_DB_METER_SWITCH_TIME || 300000;
export const MIXER_CYCLE_DATA_TIME =
  process.env.REACT_APP_NEXT_MIXER_UPDATE_TIME || 100000;
export const MIXER_LIVE_DATA_RENEW_TIME =
  process.env.REACT_APP_MIXER_LIVE_DATA_RENEW_TIME || 50000;
