export const tpOverviewMockResp = {
  "TGM-4": {
    Shift_A: {
      Production: 3342,
      Power: 48.97,
      StopTime: 421,
      Speed: 0,
    },
    Shift_B: {
      Production: 9568,
      Power: 12.58,
      StopTime: 57.73,
      Speed: 307,
    },
    Shift_C: {
      Production: 309,
      Power: 0,
      StopTime: 475,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 2.37,
    OR: 0,
  },
  "TGM-3": {
    Shift_A: {
      Production: 59257,
      Power: 91.21,
      StopTime: 213,
      Speed: 0,
    },
    Shift_B: {
      Production: 16894,
      Power: 25.37,
      StopTime: 31.73,
      Speed: 282,
    },
    Shift_C: {
      Production: 90776,
      Power: 0,
      StopTime: 109.99,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 42.09,
    OR: 0,
  },
  "TGM-2": {
    Shift_A: {
      Production: 2,
      Power: 9.57,
      StopTime: 479,
      Speed: 0,
    },
    Shift_B: {
      Production: 0,
      Power: 4.29,
      StopTime: 109.42,
      Speed: 0,
    },
    Shift_C: {
      Production: 5546,
      Power: 2.72,
      StopTime: 480,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 0,
    OR: 0,
  },
  "TGM-1": {
    Shift_A: {
      Production: 535,
      Power: 0,
      StopTime: 454,
      Speed: 0,
    },
    Shift_B: {
      Production: 1733,
      Power: 0,
      StopTime: 91.73,
      Speed: 73,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 0.38,
    OR: 0,
  },
  "Norden-1": {
    Shift_A: {
      Production: 128,
      Power: 0,
      StopTime: 455,
      Speed: 0,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 109.42,
      Speed: 0,
    },
    Shift_C: {
      Production: 22390,
      Power: 0,
      StopTime: 480,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 0.13,
    OR: 0,
  },
  "Norden-2": {
    Shift_A: {
      Production: 2854,
      Power: 0,
      StopTime: 430,
      Speed: 0,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 109.42,
      Speed: 0,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: 0,
    },
    RunningStatus: 0,
    OEE: 2.97,
    OR: 0,
  },
  "PACMAC-1": {
    Shift_A: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 111.38,
      Speed: null,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    RunningStatus: 0,
    OEE: 0,
    OR: 0,
  },
  "PACMAC-2": {
    Shift_A: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 111.38,
      Speed: null,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    RunningStatus: 0,
    OEE: 0,
    OR: 0,
  },
  "PACMAC-3": {
    Shift_A: {
      Production: 0,
      Power: 0,
      StopTime: 479.9,
      Speed: null,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 110.1,
      Speed: null,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    RunningStatus: 0,
    OEE: 0,
    OR: 0,
  },
  "PACMAC-4": {
    Shift_A: {
      Production: 46163,
      Power: 0,
      StopTime: 68.73,
      Speed: null,
    },
    Shift_B: {
      Production: 7116,
      Power: 0,
      StopTime: 46.47,
      Speed: null,
    },
    Shift_C: {
      Production: 35268,
      Power: 0,
      StopTime: 127.92,
      Speed: null,
    },
    RunningStatus: 0,
    OEE: 60.11,
    OR: 0,
  },
  "PACMAC-5": {
    Shift_A: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    Shift_B: {
      Production: 0,
      Power: 0,
      StopTime: 110.56,
      Speed: null,
    },
    Shift_C: {
      Production: 0,
      Power: 0,
      StopTime: 480,
      Speed: null,
    },
    RunningStatus: 0,
    OEE: 0,
    OR: 0,
  },
};

export const tpUtilityConstant = {
  Sound: {
    "Meter-1": 79.48,
    "Meter-2": 54,
    "Meter-3": 45,
  },
  Bag: {
    "Bag-1": 0,
    "Bag-2": 0,
    "Bag-3": 0,
  },
  Mixer: {
    "Mixer-1": {
      BatchNo: 0,
      Ph: 0,
      Viscosity: 0,
    },
    "Mixer-2": {
      BatchNo: 0,
      Ph: 0,
      Viscosity: 0,
    },
    "Mixer-3": {
      BatchNo: 0,
      Ph: 0,
      Viscosity: 0,
    },
    "Mixer-4": {
      BatchNo: 0,
      Ph: 6.18,
      Viscosity: 132000,
    },
    "Mixer-5": {
      BatchNo: 0,
      Ph: 0,
      Viscosity: 0,
    },
  },
  Shift: {
    "Shift-A": {
      Power: 723.06,
      Steam: 226.16,
      Air: 3926.1,
      Water: 0,
    },
    "Shift-B": {
      Power: 401.06,
      Steam: 131.75,
      Air: 992.39,
      Water: 0,
    },
    "Shift-C": {
      Power: 702.94,
      Steam: 1.58,
      Air: 4056.68,
      Water: 0,
    },
  },
};
